[package]
name = "kmeans"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
itertools = "0.14.0"
linfa = { version = "0.8.1", features = ["ndarray-linalg"] }
linfa-clustering = "0.8.1"
linfa-nn = "0.8.1"
ndarray = "0.17.2"
polars = { version = "0.53.0", features = ["dtype-full", "lazy", "ndarray", "full"] }
reqwest = { version = "0.13.3", features = ["blocking"] }
tempfile = "3.27.0"
